<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-F6KMT2A" failures="1" tests="6" name="LoginTest.autoLogin" time="36.719" errors="0" timestamp="2019-10-02T10:51:38 ICT" skipped="0">
  <testcase classname="LoginTest.autoLogin" name="verifyLog" time="6.459"/>
  <testcase classname="LoginTest.autoLogin" name="verifyLoginFailed1" time="6.319"/>
  <testcase classname="LoginTest.autoLogin" name="verifyLoginFailed2" time="6.462"/>
  <testcase classname="LoginTest.autoLogin" name="verifyLoginFailed3" time="6.502"/>
  <testcase classname="LoginTest.autoLogin" name="verifyLoginFailed4" time="5.894"/>
  <testcase classname="LoginTest.autoLogin" name="verifyAlreadyLogin" time="5.083">
    <failure message="expected:&lt;&gt; but was:&lt;Tài khoản của bạn đang đăng nhập trên một trình duyệt khác. Vui lòng bấm TIẾP TỤC để đăng xuất trình duyệt cũ và đăng nhập vào trình duyệt mới này.&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<Tài khoản của bạn đang đăng nhập trên một trình duyệt khác. Vui lòng bấm TIẾP TỤC để đăng xuất trình duyệt cũ và đăng nhập vào trình duyệt mới này.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at LoginTest.autoLogin.verifyAlreadyLogin(autoLogin.java:138)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAlreadyLogin -->
</testsuite> <!-- LoginTest.autoLogin -->
